version: '3'
services:
    api:
        container_name: api-container
        restart: always
        image: node:16
        working_dir: /usr/src/app
        command: bash -c "npm install --production && npm run debug"
        volumes:
            - ./package.json:/usr/src/app/package.json
            - ./dist/:/usr/src/app/dist/
        ports: 
            - "5050:5050"
            - "9222:9222"
        links:
            - dbSql
            
    dbSql:
        container_name: psql-container
        image: postgres
        restart: always
        ports:
            - "15432:5432"
        volumes:
            - ./PostgreSQL:/var/lib/postgresql/data 
        environment:
            POSTGRES_PASSWORD: baggio123
            POSTGRES_USER: baggio
            POSTGRES_DB: totvs