version: '3'
services:
    mongo:
        container_name: mongo-container
        image: mongo
        restart: always
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
    
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - "8081:8081"

    api:
        container_name: api-container
        restart: always
        build: .
        image: clean-node-api
        command: npm run debug
        volumes:
            - ./package.json:/usr/src/app/package.json
            - ./dist:/usr/src/app/dist
        ports: 
            - "5050:5050"
            - "9222:9222"
        links:
            - mongo